---
- name: Upgrade packages
  apt: upgrade=yes
  tags:
    - packages

- name: Enable fsckfix during boot
  lineinfile:
    dest: /etc/default/rcS
    regexp: '^FSCKFIX='
    line: "FSCKFIX=yes"
    backup: yes
  tags:
    - rcS

- name: Remove /tmp/* files during boot
  lineinfile:
    dest: /etc/default/rcS
    regexp: '^TMPTIME='
    line: "TMPTIME=0"
    backup: yes
  tags:
    - rcS

- name: Modify Unattended upgrade settings
  replace:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: '^//Unattended-Upgrade::Mail "root";', replace: 'Unattended-Upgrade::Mail "root";' }
    - { regexp: '^//Unattended-Upgrade::Remove-Unused-Dependencies "false";', replace: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' }
  tags:
    - unattended-upgrades

- name: Autoremove unused packages
  command: apt-get -y autoremove
  register: autoremove_output
  changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"
